export const reducerCases = {
  SET_USER_INFO: "SET_USER_INFO",
  SET_NEW_USER: "SET_NEW_USER",
  SET_CONTACTS_PAGE: "SET_CONTACTS_PAGE",
  CHANGE_CHAT_USER: "CHANGE_CHAT_USER",
  SET_MESSAGES: "SET_MESSAGES",
  SET_SOCKET: "SET_SOCKET",
  ADD_MESSAGE: "ADD_MESSAGE",
  SET_MESSAGE_SEARCH: "SET_MESSAGE_SEARCH",
  SET_THEME: "SET_THEME",
  SET_THEME_PAGE: "SET_THEME_PAGE",
  SET_USER_CONTACTS: "SET_USER_CONTACTS",
  SET_ONLINE_USERS: "SET_ONLINE_USERS",
};
